spring:
  cloud:
    aws:
      s3:
        bucket: cloud-work-seonghoon-uploads
  config:
    import:
      - aws-parameterstore:/cloud-work/prod/db/
      - aws-parameterstore:/cloud-work/prod/cloudfront/
  datasource:
    url: "${url}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${username}"
    password: "${password}"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: false
    hibernate:
      ddl-auto: validate

cloudfront:
  domain: "${domain}"
  key-pair-id: "${key-pair-id}"
  private-key: "${private-key}"

management:
  info:
    env:
      enabled: true

info:
  app:
    message: ${info}
