spring:
  cloud:
    aws:
      s3:
        bucket: cloud-work-seonghoon-uploads
  config:
    import: aws-parameterstore:/cloud-work/prod/db/
  datasource:
    url: "${url}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${username}"
    password: "${password}"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: false
    hibernate:
      ddl-auto: validate

cloudfront:
  domain: https://d3hgy7tcqt9u54.cloudfront.net
  key-pair-id: K3SI7PZC8QZQZC
  private-key: "${private-key}"

management:
  info:
    env:
      enabled: true

info:
  app:
    message: ${info}
